---
- name: 1.Check if PHP repo is already configured.
  stat: path={{ php_repofile_path }}
  register: php_repofile_result
 
- name: 2.Install PHP repo.
  yum:
    name: "{{ php_repo_url }}"
    state: present
  register: result
  when: not php_repofile_result.stat.exists
 
- name: 3.Import PHP GPG key.
  rpm_key:
    key: "{{ php_repo_gpg_key_url }}"
    state: present
  when: not php_repofile_result.stat.exists

- name: 4.Install PHP and packages
  yum:
    name: "{{ item }}"
    state: present
    update_cache: yes
    enablerepo: remi-php71
  with_items:
    - php
    - php-mysql
    - php-pecl-apcu
    - php-pecl-zendopcache

- name: 5.Enable remi repository
  ini_file:
    path: /etc/yum.repos.d/remi.repo
    section: remi
    option: enabled
    value: 1

- name: 6.Disable php56 repository
  ini_file:
    path: /etc/yum.repos.d/remi.repo
    section: remi-php56
    option: enabled
    value: 0

- name: 7.Disable php70 repository
  ini_file:
    path: /etc/yum.repos.d/remi-php70.repo
    section: remi-php70
    option: enabled
    value: 0

- name: 8.Enable php71 repository
  ini_file:
    path: /etc/yum.repos.d/remi-php71.repo
    section: remi-php71
    option: enabled
    value: 1




